### ISSUE TITLE
MQTT Source Connector not supporting shared-subscriber topics

### ISSUE THREAD

**Issue by orbiran88** [Landoop/stream-reactor#542] opened 2019-02-05 12:32 UTC
Stream Reactor version: 1.2.1
MQTT Broker: VerneMQ

### Expected behaviour:
Connector config:
```
{
	"name": "Example_MQTT_Source_Connector",
	"connector.class": "com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceConnector",
	"tasks.max": "1",
	"connect.mqtt.hosts": "tcp://mqttbroker:1883",
	"connect.mqtt.connection.clean": "false",
	"connect.mqtt.service.quality": "2",
	"connect.mqtt.kcql": "INSERT INTO kafka_topic SELECT * FROM `$share/group_name/mqtt_topic_name` 
}
```

I expect to get messages that were published to `mqtt_topic_name` to pass to `kafka_topic`.

### Observed
The connector ignores the mqtt messages that came from `kafka_topic`

### Code & Reason
 The reason is that the function `compareTopic` in `MqttManager.scala` trying to compare the source topic name from the KCQL `$share/group_name/mqtt_topic_name` to the source topic name that came from the mqtt message `mqtt_topic_name`, that compare results in `false` and the MqttWriter drops the message.

https://github.com/Landoop/stream-reactor/blob/c8d2c6a16c65f574047c4e843b8454e29695351f/kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManager.scala#L58

### Fix
I done a quick fix for that, not something to PR.. 

add the `$share/group_name` to the `messageArrived` function on `MqttWriter`.

```
override def messageArrived(topic: String, message: MqttMessage): Unit = {

    val matched = sourceToTopicMap
      .filter(t => checkTopic("$share/group_name/" + topic, t._2))
      .map(t => t._2.getSource)
```

**Comment by orbiran88** [comment] 2019-02-10 09:17
@stheppi Hi, this is only the test case for shared-subscriber topic.. did you pushed all the code changes? thanks!

**Comment by stheppi** [comment] 2019-02-10 14:52
Hi @orbiran88,
 I didn't provide the gix. @sotirissl said he can't reproduce. He has put the unit test in.

On the match topic. As you know mqtt allows single(+) and multi-level(#). The connector allows to subscribe with wildcards. So a message Ma on topic A needs to be matched against the Kcql statement. The connector allows multi statements. Hence the `compareTopic`.

 I see your proposed solution uses `endwith`. Would be good to understand why you need .endwith.
You are subscribing to `$share/group_name/mqtt_topic_name`, right? And your messages are on `mqtt_topic_name`. What if you're subscribing with multi level? `endwith` won't work then, no?  If a shared subscription is used the idea is to drop `share/groupid` and then use the same matching logic.

**Comment by orbiran88** [comment] 2019-02-10 20:28
Yep, you totally right.. 
This can be achieved with this little addition: `.replaceAll("\\$share/.*?/", "")`

```
  private def compareTopic(actualTopic: String, subscribedTopic: String): Boolean = {
        actualTopic.matches(subscribedTopic.replaceAll("\\$share/.*?/", "")
            .replaceAll("\\+", "[^/]+")
            .replaceAll("#", ".+")
            .replace("$", ".+"))
  }
```

**Comment by stheppi** [comment] 2019-02-14 09:51
PR merged. Thank you

**Closed by stheppi** 2019-02-14 09:51 UTC
